// Generates THIRD-PARTY-NOTICES.md from the licenses of the packages that are
// actually shipped to users: the production dependency tree (the app bundle) plus
// the Workbox runtime that vite-plugin-pwa bundles into the service worker.
//
// Run with: npm run notices

import { execSync } from 'node:child_process'
import { readFileSync, existsSync, readdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const LICENSE_FILES = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'LICENCE.md', 'COPYING']

function productionPackageDirs() {
  const out = execSync('npm ls --omit=dev --all --parseable', { encoding: 'utf8' })
  return out
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.includes('node_modules') && !l.includes('playwright'))
}

function workboxRuntimeDirs() {
  const root = 'node_modules'
  if (!existsSync(root)) return []
  return readdirSync(root)
    .filter((name) => name.startsWith('workbox-') && name !== 'workbox-build' && name !== 'workbox-cli')
    .map((name) => `${process.cwd()}/${root}/${name}`)
}

function findLicenseText(dir) {
  for (const file of LICENSE_FILES) {
    const path = `${dir}/${file}`
    if (existsSync(path)) return readFileSync(path, 'utf8').trim()
  }
  return null
}

function collect() {
  const dirs = [...new Set([...productionPackageDirs(), ...workboxRuntimeDirs()])]
  const packages = []
  for (const dir of dirs) {
    let pkg
    try {
      pkg = require(`${dir}/package.json`)
    } catch {
      continue
    }
    if (!pkg.name || pkg.name === 'render-my-web-app') continue
    const author =
      typeof pkg.author === 'string' ? pkg.author : pkg.author?.name ? pkg.author.name : ''
    packages.push({
      name: pkg.name,
      version: pkg.version,
      license: pkg.license ?? 'UNKNOWN',
      author,
      text: findLicenseText(dir),
    })
  }
  packages.sort((a, b) => a.name.localeCompare(b.name))
  return packages
}

function render(packages) {
  const licenses = [...new Set(packages.map((p) => p.license))].sort()
  let md = `# Third-Party Notices

This application bundles open-source software. Each package below is distributed
under its own license; the full license texts are reproduced here to satisfy the
attribution requirements (e.g. MIT/BSD/Apache-2.0).

This file is generated by \`npm run notices\` — do not edit it by hand.

Bundled packages: ${packages.length}. Licenses in use: ${licenses.join(', ')}.

---
`
  for (const p of packages) {
    md += `\n## ${p.name}@${p.version}\n\nLicense: ${p.license}${p.author ? ` — ${p.author}` : ''}\n`
    if (p.text) {
      md += `\n\`\`\`\n${p.text}\n\`\`\`\n`
    } else {
      md += `\n_No license file was bundled with this package; it declares \`${p.license}\` in its \`package.json\`._\n`
    }
    md += `\n---\n`
  }
  return md
}

const packages = collect()
writeFileSync('THIRD-PARTY-NOTICES.md', render(packages))
console.log(`Wrote THIRD-PARTY-NOTICES.md for ${packages.length} packages.`)
